"""Added portfolio model

Revision ID: 3e30a663dd4f
Revises: 6a9d251d9e65
Create Date: 2025-03-15 02:30:47.145712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e30a663dd4f'
down_revision: Union[str, None] = '6a9d251d9e65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
