"""Added ContactMessage and AboutMe models

Revision ID: ac15f4b2ff2b
Revises: 7a560d834582
Create Date: 2025-03-15 09:58:14.083558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac15f4b2ff2b'
down_revision: Union[str, None] = '7a560d834582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
