name: Build Blog Backend

on: 
  push:
    branches:
      - main
      - portfolio
  pull_request:
    branches:
      [main, portfolio]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
     
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Login to DockerHub
        run: docker login -u ${{vars.DOCKER_USERNAME}} -p ${{secrets.DOCKER_TOKEN}}

      - name: Build docker image
        run: |
          cd ./../..
          ls -la
          docker build -t blog_backend .

      - name: Tag image
        run: docker tag blog_backend:latest ${{vars.DOCKER_USERNAME}}/blog_backend:${{github.sha}}

      - name: Push image
        run: docker push ${{vars.DOCKER_USERNAME}}/blog_backend:${{github.sha}}